Improve performance of autoupdate checking (#66)
This reduced the startup time of autoupdate without `--background`
around 14ms for me.
Now the main culprit is checking whether the current user is the
`zgenom_owner` which takes 7-9ms. Locking takes around 3ms.

diff --git a/functions/__zgenom_autoupdate b/functions/__zgenom_autoupdate
--- a/functions/__zgenom_autoupdate
+++ b/functions/__zgenom_autoupdate
@@ -1,29 +1,29 @@
 #!/usr/bin/env zsh
 
-function __zgenom_check_interval() {
-    local last_update
-    if [[ ! -f $1 ]]; then
-        # We've never run, set the last run time to the dawn of time, or at
-        # least the dawn of posix time.
-        last_update=0
-        printf 0 > $1
-    else
-        read -r last_update < $1
-    fi
-    expr $2 - $last_update
+# Bail out when zsh/system is not available
+zmodload zsh/system || {
+    __zgenom_err 'Could not load `zsh/system` which is needed for autoupdate. Please create an issue.'
+    return 1
 }
 
 function __zgenom_should_autoupdate() {
-    local min_interval=$(( $1 * 86400 )) # days to seconds
-    local last_update=$(__zgenom_check_interval "$ZGEN_DIR/.zgenom-$2-lastupdate" $3)
+    local days=$1
+    local file="$ZGEN_DIR/.zgenom-$2-lastupdate"
+    local last_update
+    if [[ ! -f $file ]]; then
+        # We've never run, create the lastupdate-file and set now as interval.
+        printf 0 > $file
+        last_update=$now
+    else
+        last_update=$(( $now - $(< $file) - $days * 86400 ))
+    fi
 
-    if [[ $last_update -gt $min_interval ]]; then
-        if [[ -n "$4" ]]; then
-            local days=$(( $last_update / 86400 ))
-            if [[ $days -le 18840 ]]; then
-                __zgenom_out "It has been $days days since your last $2 update."
-            else
+    if [[ $last_update -ge 0 ]]; then
+        if [[ -n $verbose ]]; then
+            if [[ $last_update -eq $now ]]; then
                 __zgenom_out "Never automatically updated '$2'."
+            else
+                __zgenom_out "It has been $(( $last_update / 86400 + $days)) days since your last $2 update."
             fi
         fi
         return 0
@@ -31,41 +31,43 @@ function __zgenom_should_autoupdate() {
     return 1
 }
 
-# Don't update if we're running as different user than whoever
-# owns ZGEN_DIR. This prevents sudo runs from leaving root-owned
-# files & directories in ZGEN_DIR that will break future update
-# runs by the user.
-#
-# Using ls and awk instead of stat because stat has incompatible arguments
-# on linux, macOS and FreeBSD.
 function __zgenom_autoupdate() {
-    local zgen_owner=$(command ls -ld $ZGEN_DIR | awk '{print $3}')
+    # Using ls and awk instead of stat because stat has incompatible arguments
+    # on linux, macOS and FreeBSD.
+    local zgenom_owner=$(command ls -ld $ZGEN_DIR | awk '{print $3}')
     local updated=0
 
-    if [[ "$zgen_owner" == "$USER" ]]; then
-        zmodload zsh/system
+    # Don't update if we're running as different user than whoever
+    # owns ZGEN_DIR. This prevents sudo runs from leaving root-owned
+    # files & directories in ZGEN_DIR that will break future update
+    # runs by the user.
+    if [[ "$zgenom_owner" == "$USER" ]]; then
         local lockfile="$HOME/.zgenom-autoupdate-lock"
         printf '' > "$lockfile"
-        if ! which zsystem &> /dev/null || zsystem flock -t 1 "$lockfile"; then
+        # Create lock, don't retry to obtain a lock
+        if zsystem flock -t 0 "$lockfile" &>/dev/null; then
             local now=$(command date '+%s')
 
             # Update self
-            if [[ -n $self ]] && __zgenom_should_autoupdate $self system $now $verbose; then
+            if [[ -n $self ]] && __zgenom_should_autoupdate $self system; then
                 [[ -n $verbose ]] && __zgenom_err "Updating zgenom ..."
-                zgenom selfupdate --no-reset && __zgenom_out
-                updated=1
+                zgenom selfupdate --no-reset && __zgenom_out && updated=1
             fi
 
             # Update plugins
-            if [[ -n $plugin ]] && __zgenom_should_autoupdate $plugin plugin $now $verbose; then
+            if [[ -n $plugin ]] && __zgenom_should_autoupdate $plugin plugin; then
                 [[ -n $verbose ]] && __zgenom_err "Updating plugins ..."
-                zgenom update --no-reset
-                updated=1
+                zgenom update --no-reset && updated=1
             fi
 
+            # Reset only when updated
             [[ $updated -ge 1 ]] && zgenom reset && __zgenom_out
 
-            command rm -f "$lockfile"
+            # Release the lock
+            printf '' > "$lockfile"
+
+            # Remove lock file
+            { command rm -f "$lockfile" } &!
         fi
     else
         if [[ -n "$DEBUG" ]]; then
